apiVersion: v1
kind: Service
metadata:
  name: jagan-service
  #namespace: jagan-service
  labels:
    app: jagan-app
spec:
  type: LoadBalancer
  selector:
    app: jagan-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP