apiVersion: v1
kind: Service
metadata:
  name: jagan-service
  labels:
    app: jagan-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-pod
  ports:
    - name: http
      port: 5111
      targetPort: 5000
      protocol: TCP